[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "us"
version = "4.0.0.dev0"
description = "US state metadata"
readme = "README.md"
urls.Homepage = "https://github.com/unitedstates/python-us/"
urls."Issue tracker" = "https://github.com/unitedstates/python-us/issues"
requires-python = ">=3.8"
authors = [{ name = "Jeremy Carbaugh", email = "jeremy@jcarbaugh.com" }]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]
license = { file = "LICENSE"}

dependencies = ['jellyfish']

[project.scripts]
states = "us.cli.states:main"

[dependency-groups]
dev = ['ruff', 'pytest', 'pytz']

[tool.ruff]
line-length = 120
target-version = "py38"
