name: Tests

on:
  pull_request:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Check code format with Ruff
        run: uv run ruff format --check us

  testing:
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 7
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Test with pytest
        run: uv run pytest .

  building:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.14"

      - name: Build package
        run: uv build --wheel

      - uses: actions/upload-artifact@v7
        with:
          name: wheels
          path: ./dist/*.whl
